//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_PF_KendallBonilla_RandyArtavia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PAV_PF_KendallBonilla_RandyArtaviaEntities : DbContext
    {
        public PAV_PF_KendallBonilla_RandyArtaviaEntities()
            : base("name=PAV_PF_KendallBonilla_RandyArtaviaEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleVentas> DetalleVentas { get; set; }
        public virtual DbSet<GenerosLiterarios> GenerosLiterarios { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
